apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}{{ .Values.app.suffix }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.container.port }}
  selector:
    app: {{ .Values.app.name }}{{ .Values.app.suffix }}