apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-deployment
  namespace: mh-caso1
  labels:
    app: alpine-netcat
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: alpine-netcat
  template:
    metadata:
      name: alpine-pod
      labels:
        app: alpine-netcat
    spec:
      containers:
        - name: alpine-container
          image: alpine:3.19.0
          command: [ "/bin/sh", "-c", "apk add envsubst && while true; do { echo -e 'HTTP/1.1 200 OK\r\n'; envsubst < /data/index.html; } | nc -l -p 8080; done" ]
          ports:
            - name: ncport
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: html-index-file
              mountPath: /data
      volumes:
        - name: html-index-file
          configMap:
            name: page-html
      restartPolicy: Always